### ISSUE TITLE
Create page 2 of webpage - after user signs into application, they are shown a page with 9 empty spots that can be used to "save" items on their "Wishlist." They are then given the opportunity to "shop" at a variety of pre-determined stores, which offer a variety of pre-determined items, which can be added to their Wishlist.

### ISSUE THREAD

**Issue by matthewheimark** [matthewheimark/project2#20]

**Comment by andrewpetersondev** [comment]
I am confused about what this issue is? Can you post a picture? I am designing a wishlist page using materialize card reveals because I think it would look great and connect to our user's data in a unique way.

**Comment by matthewheimark** [comment]
This was an issue that I created and closed. It's the wishlist page with the 9 placeholders. 
![Screen Shot 2019-08-11 at 11 04 42 PM](https://user-images.githubusercontent.com/46358080/62845290-7243cc80-bc8c-11e9-841e-842f235206e5.png)

**Comment by andrewpetersondev** [comment]
Did you add a carousel feature? I really like that. Did you do that with materialize in a grid?
